### ISSUE TITLE
是否需要配置ssl自签名证书？对比electrumx-proxy有什么优势？

### ISSUE THREAD

**Issue by yuppiesnotzhuhao** [WizzWallet/elex-proxy#3]
rt

**Comment by iota9star** [comment]
If you want to share your proxy with others, using an SSL certificate is optional and has nothing to do with elex-proxy. Unlike electrumx-proxy, elex-proxy is much faster and way easier to set up and use.

**Comment by yuppiesnotzhuhao** [comment]
> If you want to share your proxy with others, using an SSL certificate is optional and has nothing to do with elex-proxy. Unlike electrumx-proxy, elex-proxy is much faster and way easier to set up and use.

electrumx-proxy只支持tcp，elex-proxy支持tcp+ssl吗？

**Comment by iota9star** [comment]
Elex-proxy is like a revamped version of electrumx-proxy, but it's all about using the WebSocket protocol for swapping data. Anyway, it's not related to what you were talking about.

**Comment by yuppiesnotzhuhao** [comment]
> Elex-proxy is like a revamped version of electrumx-proxy, but it's all about using the WebSocket protocol for swapping data. Anyway, it's not related to what you were talking about.

I downloaded and unzipped elex-proxy-Linux-x86_64-musl.tar.gz on ubuntu and got elex-proxy, but I don't know how to run it

**Comment by iota9star** [comment]
You can directly execute the script below. If you need additional configuration, please follow the instructions in the README.
```shell
./elex-proxy
```
